export const infoproductos = [
    {
        id: 1,
        title: "Agenda 2021",
        info: "Agenda 2020 Moove, 160 hojas, 100 stickers",
        price: 900,
        pictureUrl: "https://i.imgur.com/hakVwzv.jpg",
        description: 'Agenda de planeamiento semanal (semana a la vista) 15x21 cm',
        categoryId: "Agendas",
        stock: 10,
        initial: 1,
    },
    {
        id: 2,
        title: "Cuaderno",
        info: "Cuadernos Avon,160 hojas cuadriculadas, varios diseños",
        price: 130,
        pictureUrl: "https://i.imgur.com/AatHQ3z.jpg",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        categoryId:"Cuadernos",
        stock: 8,
        initial: 1,
       
    },
    {
        id: 3,
        title: "Calculadora Cientifica",
        info: "Calculadora Marca: Daihatsu",
        price: 2900,
        description:'Calculadora cientifica',
        pictureUrl:"https://i.imgur.com/uKURaVr.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Calculadoras",
    },
    {
        id: 4,
        title: "Resaltadores fluor",
        info: "Una unidad, colores surtidos",
        price: 75,
        pictureUrl: "https://i.imgur.com/4ZHLbST.jpg",
        description: 'Resaltadores fluor, 10 colores disponibles',  
        initial: 1,
        stock: 6,
        categoryId: "Resaltadores",
    },
    {
        id: 5,
        title: "Resaltadores pastel",
        info: "Una unidad, colores surtidos",
        price: 120,
        pictureUrl: "https://i.imgur.com/vlg3cd1.jpg",
        description: 'Resaltadores pastel, 8 colores disponibles',  
        initial: 1,
        stock: 6,
        categoryId: "Resaltadores",
    },
    {
        id: 6,
        title: "Cuaderno A5",
        info: "Anillado, 80 hojas rayadas y elastico",
        price: 890,
        pictureUrl: "https://i.imgur.com/FWaD2yh.jpg",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',   
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 7,
        title: "Agendas 2021 Poket",
        info: " Tres diseños disponibles, semana a la vista",
        price: 870,
        pictureUrl: "https://i.imgur.com/x0eC7E3.jpg",
        description: "Agenda de organizacion semanal (semana a la vista)",
                stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },{
        id: 8,
        title: "Agenda 2021 A5",
        info: "Dia por dia, stickers y calendario a la vista mensual",
        description: "Agenda de planeamiento semanal (semana a la vista)",
                price: 1298,
        pictureUrl:"https://i.imgur.com/Q8RS6f0.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },{
        id: 9,
        title: "Carpeta folios",
        info: "Precio por unidad, carpeta 10 folios con broche",
        description: 'Carpeta folio A4, super amplia y funcional',
        price: 498,
        pictureUrl:"https://i.imgur.com/2dQnNyG.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 10,
        title: "Agenda 2021 Astrologica",
        info: "Tarot, signos, dia por dia, stickers",
        description: "Agenda de planeamiento semanal (semana a la vista)",
      price: 1267,
        pictureUrl:"https://i.imgur.com/GTHusE4.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },
{
        id: 11,
        title: "Agenda 2021 Floral",
    info: "Agenda dia por dia, anillada",
    description: "Agenda de planeamiento semanal (semana a la vista)",
            price: 1156,
        pictureUrl:"https://i.imgur.com/5RQXtZQ.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },
    {
        id: 12,
        title: "Cartuchera gris",
        info: "Un cierre principal, bolsillo delante y en el interior",
        description: 'Un cierre principal, bolsillo delante y en el interior',
        price: 780,
        pictureUrl:"https://i.imgur.com/RCHwIT3.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    },
    {
        id: 13,
        title: "Cartuchera fucsia",
        info: "Un solo cierre, super amplia y practica",
        description: 'Cartuchera fucsia, bolsillo central, super amplio',
        price: 893,
        pictureUrl:"https://i.imgur.com/VFNqES9.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    },
    {
        id: 14,
        title: "Agenda 2021 Marmol",
        info: "Agenda dia por dia, anillada",
        description: "Agenda de planeamiento semanal (semana a la vista)",
                price: 879,
        pictureUrl:"https://i.imgur.com/J37nuac.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },
    {
        id: 15,
        title: "Cuaderno A4 Patagonia",
        info: "Cuaderno universitario, anillado",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        price: 786,
        pictureUrl:"https://i.imgur.com/4MuQlqA.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 16,
        title: "Cuadernos A5",
        info: "Cuaderno A5 anillado, varios diseños",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        price: 678,
        pictureUrl:"https://i.imgur.com/SRqdtSV.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 17,
        title: "Cuaderno universitario",
        info: "Cuaderno A4 anillado tematico",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        price: 893,
        pictureUrl:"https://i.imgur.com/y77Qc7I.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 18,
        title: "Carpeta 3 ganchos",
        info: "Carpetas A4 en colores pasteles",
        description: 'Aptas archivo o para transporte de documentos',
        price: 658,
        pictureUrl:"https://i.imgur.com/oTuVx3y.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 19,
        title: "Mochila Escolar",
        info: "Mochila escolar super amplia",
        description: 'Mochila super practica y canchera para el dia a dia',
        price: 658,
        pictureUrl:"https://i.imgur.com/uJ0IKbS.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    }, {
        id: 20,
        title: "Mochila Escolar",
        info: "Mochila escolar super amplia",
        description: 'Mochila super practica y canchera para el dia a dia',
        price: 658,
        pictureUrl:"https://i.imgur.com/HhMKFfI.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    }, {
        id: 21,
        title: "Mochila Escolar",
        info: "Mochila escolar super amplia",
        description: 'Mochila super practica y canchera para el dia a dia',
        price: 667,
        pictureUrl:"https://i.imgur.com/Qek3E4w.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    }, {
        id: 22,
        title: "Mochila Escolar",
        info: "Mochila escolar super amplia",
        description: 'Mochila super practica y canchera para el dia a dia',
        price: 658,
        pictureUrl:"https://i.imgur.com/bmft3CD.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    }, {
        id: 23,
        title: "Mochila Escolar",
        info: "Mochila escolar super amplia",
        description: 'Mochila super practica y canchera para el dia a dia',
        price: 658,
        pictureUrl:"https://i.imgur.com/dFBjyNY.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    }, {
        id: 24,
        title: "Mochila Escolar",
        info: "Mochila escolar super amplia",
        description: 'Mochila super practica y canchera para el dia a dia',
        price: 658,
        pictureUrl:"https://i.imgur.com/it5UHhE.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    },

];

