export const infoproductos = [
    {
        id: 1,
        title: "Agenda 2021",
        info: "Agenda 2020 Moove, 160 hojas, 100 stickers",
        price: "$900",
        pictureUrl: "https://i.imgur.com/hakVwzv.jpg",
        description: 'Agenda de planeamiento semanal (semana a la vista) 15x21 cm &nbsp Tapas duras engomadas en colores pastel con número calado y cierre elástico. Hojas de extrablanco de 70 gramos y Anillada con doble espiral metálico muy resistente Cada mes esta diferenciado en una tonalidad pastel diferente Total de páginas 144Además-Datos personales y claves -Tips para optimizar uso-Calendario 2021 y 2022 -Cuadro de Gastos            -Planner Anual -Hojas de uso libre en Bullet Journal -Indice de contactos-Doble sobre de papel para documentación',
        categoryId: "Agendas",
        stock: 10,
        initial: 3,
    },
    {
        id: 2,
        title: "Cuaderno",
        info: "Cuadernos Avon,160 hojas cuadriculadas, varios diseños",
        price: "$130",
        pictureUrl: "https://i.imgur.com/AatHQ3z.jpg",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        stock: 8,
        initial: 2,
        categoryId:"Cuadernos",
    },
    {
        id: 3,
        title: "Calculadora Cientifica",
        info: "Calculadora Marca: Daihatsu",
        price: "$2900",
        description:'Calculadora cientifica',
        pictureUrl:"https://i.imgur.com/uKURaVr.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Calculadoras",
    },
    {
        id: 4,
        title: "Resaltadores fluor",
        info: "Una unidad, colores surtidos",
        price: "$75",
        pictureUrl: "https://i.imgur.com/4ZHLbST.jpg",
        description: 'Resaltadores fluor, 10 colores disponibles',  stock: 6,
        initial: 1,
        categoryId: "Resaltadores",
    },
    {
        id: 5,
        title: "Resaltadores pastel",
        info: "Una unidad, colores surtidos",
        price: "$120",
        pictureUrl: "https://i.imgur.com/vlg3cd1.jpg",
        description: 'Resaltadores pastel, 8 colores disponibles',  stock: 6,
        initial: 1,
        categoryId: "Resaltadores",
    },
    {
        id: 6,
        title: "Cuaderno A5",
        info: "Anillado, 80 hojas rayadas y elastico",
        price: "$890",
        pictureUrl: "https://i.imgur.com/FWaD2yh.jpg",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',   
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 7,
        title: "Agendas 2021 Poket",
        info: " Tres diseños disponibles, semana a la vista",
        price: "$870",
        pictureUrl: "https://i.imgur.com/x0eC7E3.jpg",
        description: "Agenda de planeamiento semanal (semana a la vista) 7 dimensiones 15x21 cm Tapas duras engomadas en colores  pastel con número calado y cierre elástico. Hojas de extrablanco de 70 gramos y Anillada con doble espiral metálico muy resistente Cada mes esta diferenciado en una tonalidad pastel diferente Total de páginas 144Además-Datos personales y claves -Tips para optimizar uso-Calendario 2021 y 2022         -Cuadro de Gastos -Planner Anual  -Hojas de uso libre en Bullet Journal   -Indice de contactos-Doble sobre de papel para documentación",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },{
        id: 8,
        title: "Agenda 2021 A5",
        info: "Dia por dia, stickers y calendario a la vista mensual",
        description: "Agenda de planeamiento semanal (semana a la vista) 7 dimensiones 15x21 cm Tapas duras engomadas en colores  pastel con número calado y cierre elástico. Hojas de extrablanco de 70 gramos y Anillada con doble espiral metálico muy resistente Cada mes esta diferenciado en una tonalidad pastel diferente Total de páginas 144Además-Datos personales y claves -Tips para optimizar uso-Calendario 2021 y 2022         -Cuadro de Gastos -Planner Anual  -Hojas de uso libre en Bullet Journal   -Indice de contactos-Doble sobre de papel para documentación",
        price: "$1298",
        pictureUrl:"https://i.imgur.com/Q8RS6f0.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },{
        id: 9,
        title: "Carpeta folios",
        info: "Precio por unidad, carpeta 10 folios con broche",
        description: 'Carpeta folio A4, super amplia y funcional',
        price: "$498",
        pictureUrl:"https://i.imgur.com/2dQnNyG.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Carpetas",
    },
    {
        id: 10,
        title: "Agenda 2021 Astrologica",
        info: "Tarot, signos, dia por dia, stickers",
        description: "Agenda de planeamiento semanal (semana a la vista) 7 dimensiones 15x21 cm Tapas duras engomadas en colores  pastel con número calado y cierre elástico. Hojas de extrablanco de 70 gramos y Anillada con doble espiral metálico muy resistente Cada mes esta diferenciado en una tonalidad pastel diferente Total de páginas 144Además-Datos personales y claves -Tips para optimizar uso-Calendario 2021 y 2022         -Cuadro de Gastos -Planner Anual  -Hojas de uso libre en Bullet Journal   -Indice de contactos-Doble sobre de papel para documentación",
        price: "$1267",
        pictureUrl:"https://i.imgur.com/GTHusE4.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },
{
        id: 11,
        title: "Agenda 2021 Floral",
    info: "Agenda dia por dia, anillada",
    description: "Agenda de planeamiento semanal (semana a la vista) 7 dimensiones 15x21 cm Tapas duras engomadas en colores  pastel con número calado y cierre elástico. Hojas de extrablanco de 70 gramos y Anillada con doble espiral metálico muy resistente Cada mes esta diferenciado en una tonalidad pastel diferente Total de páginas 144Además-Datos personales y claves -Tips para optimizar uso-Calendario 2021 y 2022         -Cuadro de Gastos -Planner Anual  -Hojas de uso libre en Bullet Journal   -Indice de contactos-Doble sobre de papel para documentación",
        price: "$1156",
        pictureUrl:"https://i.imgur.com/5RQXtZQ.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },
    {
        id: 12,
        title: "Cartuchera gris",
        info: "Un cierre principal, bolsillo delante y en el interior",
        description: 'Un cierre principal, bolsillo delante y en el interior',
        price: "$780",
        pictureUrl:"https://i.imgur.com/RCHwIT3.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    },
    {
        id: 13,
        title: "Cartuchera fucsia",
        info: "Un solo cierra, super amplia y practica",
        description: 'Cartuchera fucsia, bolsillo central, super amplio',
        price: "$893",
        pictureUrl:"https://i.imgur.com/VFNqES9.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cartucheras",
    },
    {
        id: 14,
        title: "Agenda 2021 Marmol",
        info: "Agenda dia por dia, anillada",
        description: "Agenda de planeamiento semanal (semana a la vista) 7 dimensiones 15x21 cm Tapas duras engomadas en colores  pastel con número calado y cierre elástico. Hojas de extrablanco de 70 gramos y Anillada con doble espiral metálico muy resistente Cada mes esta diferenciado en una tonalidad pastel diferente Total de páginas 144Además-Datos personales y claves -Tips para optimizar uso-Calendario 2021 y 2022         -Cuadro de Gastos -Planner Anual  -Hojas de uso libre en Bullet Journal   -Indice de contactos-Doble sobre de papel para documentación",
       
        price: "$879",
        pictureUrl:"https://i.imgur.com/J37nuac.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Agendas",
    },
    {
        id: 15,
        title: "Cuaderno A4 Patagonia",
        info: "Cuaderno universitario, anillado",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        price: "$786",
        pictureUrl:"https://i.imgur.com/4MuQlqA.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 16,
        title: "Cuadernos A5",
        info: "Cuaderno A5 anillado, varios diseños",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        price: "$678",
        pictureUrl:"https://i.imgur.com/SRqdtSV.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 17,
        title: "Cuaderno universitario",
        info: "Cuaderno A4 anillado, tematico",
        description:'Cuaderno A4, 80 hojas rayadas o cuadriculadas, precio por unidad, diseños varios',
        price: "$893",
        pictureUrl:"https://i.imgur.com/y77Qc7I.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Cuadernos",
    },
    {
        id: 18,
        title: "Carpeta 3 ganchos",
        info: "Carpeta con etiqueta, 3 ganchos A4",
        description: 'Carpeta con tres ganchos, A4, apta hojas y folios, tanto para archivo como para estudio',
        price: "$658",
        pictureUrl:"https://i.imgur.com/oTuVx3y.jpg",
        stock: 6,
        initial: 1,
        categoryId: "Carpetas",
    },

];

